//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USGA.PerformanceTest.R1
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using Microsoft.VisualStudio.TestTools.WebTesting;
    using Microsoft.VisualStudio.TestTools.WebTesting.Rules;


    public class CustomWebtestDemo3Coded : WebTest
    {

        public CustomWebtestDemo3Coded()
        {
            this.PreAuthenticate = true;
            this.Proxy = "default";
        }

        public override IEnumerator<WebTestRequest> GetRequestEnumerator()
        {
            // Initialize validation rules that apply to all requests in the WebTest
            if ((this.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.Low))
            {
                ValidateResponseUrl validationRule1 = new ValidateResponseUrl();
                this.ValidateResponse += new EventHandler<ValidationEventArgs>(validationRule1.Validate);
            }
            if ((this.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.Low))
            {
                ValidationRuleResponseTimeGoal validationRule2 = new ValidationRuleResponseTimeGoal();
                validationRule2.Tolerance = 0D;
                this.ValidateResponseOnPageComplete += new EventHandler<ValidationEventArgs>(validationRule2.Validate);
            }

            WebTestRequest request1 = new WebTestRequest("http://www.usga.org/");
            request1.ThinkTime = 3;
            WebTestRequest request1Dependent1 = new WebTestRequest("http://fonts.gstatic.com/s/alegreyasans/v3/11EDm-lum6tskJMBbdy9aaWGgEO1vGR9ucXjKC" +
                    "o8vxU.woff");
            request1Dependent1.Headers.Add(new WebTestRequestHeader("Referer", "http://www.usga.org/"));
            request1.DependentRequests.Add(request1Dependent1);
            WebTestRequest request1Dependent2 = new WebTestRequest("http://fonts.gstatic.com/s/alegreyasans/v3/KYNzioYhDai7mTMnx_gDgtUFqmyT-Ih543PWa_" +
                    "C0ig4.woff");
            request1Dependent2.Headers.Add(new WebTestRequestHeader("Referer", "http://www.usga.org/"));
            request1.DependentRequests.Add(request1Dependent2);
            WebTestRequest request1Dependent3 = new WebTestRequest("http://fonts.gstatic.com/s/alegreyasans/v3/11EDm-lum6tskJMBbdy9aeu_tG0Yx7qqITjSOZ" +
                    "kMZIk.woff");
            request1Dependent3.Headers.Add(new WebTestRequestHeader("Referer", "http://www.usga.org/"));
            request1.DependentRequests.Add(request1Dependent3);
            WebTestRequest request1Dependent4 = new WebTestRequest("http://fonts.gstatic.com/s/alegreyasans/v3/11EDm-lum6tskJMBbdy9ae1ouKFe7zgu3OIJnK" +
                    "P8_aw.woff");
            request1Dependent4.Headers.Add(new WebTestRequestHeader("Referer", "http://www.usga.org/"));
            request1.DependentRequests.Add(request1Dependent4);
            WebTestRequest request1Dependent5 = new WebTestRequest("http://fonts.gstatic.com/s/alegreyasans/v3/TKyx_-JJ6MdpQruNk-t-PM_0Gg_psQEhwRxPwk" +
                    "VXUB8.woff");
            request1Dependent5.ThinkTime = 1;
            request1Dependent5.Headers.Add(new WebTestRequestHeader("Referer", "http://www.usga.org/"));
            
            request1.DependentRequests.Add(request1Dependent5);
            WebTestRequest request1Dependent6 = new WebTestRequest("http://fonts.gstatic.com/s/alegreyasans/v3/WfiXipsmjqRqsDBQ1bA9CgoSvwt5Jk8V5Qzz5g" +
                    "xIVhE.woff");
            request1Dependent6.Headers.Add(new WebTestRequestHeader("Referer", "http://www.usga.org/"));
            request1.DependentRequests.Add(request1Dependent6);
            WebTestRequest request1Dependent7 = new WebTestRequest("http://fonts.gstatic.com/s/alegreyasans/v3/WfiXipsmjqRqsDBQ1bA9Cjz7UTTuXWmzX65m1n" +
                    "9Ltf4.woff");
            request1Dependent7.Headers.Add(new WebTestRequestHeader("Referer", "http://www.usga.org/"));
            request1.DependentRequests.Add(request1Dependent7);
            WebTestRequest request1Dependent8 = new WebTestRequest("http://fonts.gstatic.com/s/alegreyasans/v3/11EDm-lum6tskJMBbdy9aUpiVnwz0M_Hy6Y_FZ" +
                    "jz5LA.woff");
            request1Dependent8.Headers.Add(new WebTestRequestHeader("Referer", "http://www.usga.org/"));
            request1.DependentRequests.Add(request1Dependent8);
            WebTestRequest request1Dependent9 = new WebTestRequest("http://fonts.gstatic.com/s/alegreyasans/v3/WfiXipsmjqRqsDBQ1bA9CvQp_31g0rjXKZ8Gm9" +
                    "SMcKk.woff");
            
            request1Dependent9.Headers.Add(new WebTestRequestHeader("Referer", "http://www.usga.org/"));
            request1.DependentRequests.Add(request1Dependent9);
            WebTestRequest request1Dependent10 = new WebTestRequest("http://fonts.gstatic.com/s/alegreyasans/v3/WfiXipsmjqRqsDBQ1bA9CrCg-HxJJqxN4VXdlZ" +
                    "qPV8c.woff");
            request1Dependent10.Headers.Add(new WebTestRequestHeader("Referer", "http://www.usga.org/"));
            request1.DependentRequests.Add(request1Dependent10);
            WebTestRequest request1Dependent11 = new WebTestRequest("http://www.usga.org/bin/data/feeds/ticker.json");
            request1Dependent11.Headers.Add(new WebTestRequestHeader("Accept", "*/*"));
            request1Dependent11.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json"));
            request1Dependent11.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request1Dependent11.Headers.Add(new WebTestRequestHeader("Referer", "http://www.usga.org/"));
            request1.DependentRequests.Add(request1Dependent11);
            WebTestRequest request1Dependent12 = new WebTestRequest("http://www.google.com/uds/");
            request1Dependent12.Headers.Add(new WebTestRequestHeader("Referer", "http://www.usga.org/"));
            request1Dependent12.QueryStringParameters.Add("file", "search", false, false);
            request1Dependent12.QueryStringParameters.Add("v", "1", false, false);
            request1Dependent12.QueryStringParameters.Add("hl", "en", false, false);
            request1.DependentRequests.Add(request1Dependent12);
            WebTestRequest request1Dependent13 = new WebTestRequest("http://www.usga.org/bin/data/feeds/content.path_=content.size_8.json");
            request1Dependent13.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request1Dependent13.Headers.Add(new WebTestRequestHeader("Accept", "text/plain, */*; q=0.01"));
            request1Dependent13.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request1Dependent13.Headers.Add(new WebTestRequestHeader("Referer", "http://www.usga.org/"));
            request1.DependentRequests.Add(request1Dependent13);
            WebTestRequest request1Dependent14 = new WebTestRequest("http://www.usga.org/content/usga/home-page/_jcr_content/innerPar1/latest.data.jso" +
                    "n");
            request1Dependent14.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request1Dependent14.Headers.Add(new WebTestRequestHeader("Accept", "text/plain, */*; q=0.01"));
            request1Dependent14.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request1Dependent14.Headers.Add(new WebTestRequestHeader("Referer", "http://www.usga.org/"));
            request1.DependentRequests.Add(request1Dependent14);
            WebTestRequest request1Dependent15 = new WebTestRequest("http://www.usga.org/bin/data/feeds/ticker.json");
            request1Dependent15.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request1Dependent15.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request1Dependent15.Headers.Add(new WebTestRequestHeader("Referer", "http://www.usga.org/"));
            request1.DependentRequests.Add(request1Dependent15);
            WebTestRequest request1Dependent16 = new WebTestRequest("https://beacon.sojern.com/pixel/p/7065");
            request1Dependent16.Headers.Add(new WebTestRequestHeader("Referer", "http://www.usga.org/"));
            request1Dependent16.QueryStringParameters.Add("f_v", "v5_js", false, false);
            request1Dependent16.QueryStringParameters.Add("p_v", "1", false, false);
            request1Dependent16.QueryStringParameters.Add("vid", "tou", false, false);
            request1Dependent16.QueryStringParameters.Add("cid", "", false, false);
            request1.DependentRequests.Add(request1Dependent16);
            WebTestRequest request1Dependent17 = new WebTestRequest("https://www.googleapis.com/generate_204");
            request1Dependent17.Headers.Add(new WebTestRequestHeader("Referer", "http://www.usga.org/"));
            request1.DependentRequests.Add(request1Dependent17);
            WebTestRequest request1Dependent18 = new WebTestRequest("http://clients1.google.com/generate_204");
            request1Dependent18.Headers.Add(new WebTestRequestHeader("Referer", "http://www.usga.org/"));
            request1.DependentRequests.Add(request1Dependent18);
            yield return request1;
            request1 = null;

            WebTestRequest request2 = new WebTestRequest("http://20667643p.rfihub.com/ca.html");
            request2.Headers.Add(new WebTestRequestHeader("Referer", "http://www.usga.org/"));
            request2.QueryStringParameters.Add("ver", "9", false, false);
            request2.QueryStringParameters.Add("rb", "19027", false, false);
            request2.QueryStringParameters.Add("ca", "20667643", false, false);
            request2.QueryStringParameters.Add("pe", "http%3A%2F%2Fwww.usga.org%2F", false, false);
            request2.QueryStringParameters.Add("pf", "", false, false);
            request2.QueryStringParameters.Add("ra", "6769913622395769", false, false);
            ExtractText extractionRule1 = new ExtractText();
            extractionRule1.StartsWith = "&user_id=";
            extractionRule1.EndsWith = "&";
            extractionRule1.Index = 0;
            extractionRule1.IgnoreCase = false;
            extractionRule1.UseRegularExpression = false;
            extractionRule1.HtmlDecode = true;
            extractionRule1.Required = false;
            extractionRule1.ContextParameterName = "QueryStringParam67.user_id";
            request2.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule1.Extract);
            yield return request2;
            request2 = null;

            WebTestRequest request3 = new WebTestRequest("https://3679066.fls.doubleclick.net/activityi;src=3679066;type=visit323;cat=visit" +
                    "266;ord=4616798426246.588");
            request3.Headers.Add(new WebTestRequestHeader("Referer", "http://www.usga.org/"));
            request3.QueryStringParameters.Add("", "", false, false);
            yield return request3;
            request3 = null;

            WebTestRequest request4 = new WebTestRequest("https://googleads.g.doubleclick.net/pagead/viewthroughconversion/961032657/");
            request4.ExpectedResponseUrl = "https://www.google.co.in/ads/user-lists/961032657/?fmt=1&num=1&cv=8&frm=0&url=htt" +
                "p%3A//www.usga.org/&random=1447574902&ipr=y";
            request4.Headers.Add(new WebTestRequestHeader("Referer", "http://www.usga.org/"));
            request4.QueryStringParameters.Add("random", "1450421037279", false, false);
            request4.QueryStringParameters.Add("cv", "8", false, false);
            request4.QueryStringParameters.Add("fst", "1450421037279", false, false);
            request4.QueryStringParameters.Add("num", "1", false, false);
            request4.QueryStringParameters.Add("fmt", "1", false, false);
            request4.QueryStringParameters.Add("guid", "ON", false, false);
            request4.QueryStringParameters.Add("u_h", "1113", false, false);
            request4.QueryStringParameters.Add("u_w", "1391", false, false);
            request4.QueryStringParameters.Add("u_ah", "1061", false, false);
            request4.QueryStringParameters.Add("u_aw", "1391", false, false);
            request4.QueryStringParameters.Add("u_cd", "24", false, false);
            request4.QueryStringParameters.Add("u_his", "1", false, false);
            request4.QueryStringParameters.Add("u_tz", "330", false, false);
            request4.QueryStringParameters.Add("u_java", "true", false, false);
            request4.QueryStringParameters.Add("u_nplug", "2", false, false);
            request4.QueryStringParameters.Add("u_nmime", "4", false, false);
            request4.QueryStringParameters.Add("frm", "0", false, false);
            request4.QueryStringParameters.Add("url", "http%3A//www.usga.org/", false, false);
            yield return request4;
            request4 = null;

            WebTestRequest request5 = new WebTestRequest("http://ib.adnxs.com/pxj");
            request5.Headers.Add(new WebTestRequestHeader("Referer", "http://20667643p.rfihub.com/ca.html?ver=9&rb=19027&ca=20667643&pe=http%3A%2F%2Fww" +
                        "w.usga.org%2F&pf=&ra=6769913622395769"));
            request5.QueryStringParameters.Add("bidder", "18", false, false);
            request5.QueryStringParameters.Add("seg", "378601", false, false);
            request5.QueryStringParameters.Add("action", "setuids(\'1038150087729299116\',\'1CAESEO8Y5ovr6CoOcZaDGzs2dHg\');", false, false);
            request5.QueryStringParameters.Add("redir", "", false, false);
            yield return request5;
            request5 = null;

            WebTestRequest request6 = new WebTestRequest("http://x.bidswitch.net/sync");
            request6.ThinkTime = 1;
            request6.Headers.Add(new WebTestRequestHeader("Referer", "http://20667643p.rfihub.com/ca.html?ver=9&rb=19027&ca=20667643&pe=http%3A%2F%2Fww" +
                        "w.usga.org%2F&pf=&ra=6769913622395769"));
            request6.QueryStringParameters.Add("dsp_id", "119", false, false);
            request6.QueryStringParameters.Add("user_id", this.Context["QueryStringParam67.user_id"].ToString(), false, false);
            request6.QueryStringParameters.Add("expires", "30", false, false);
            yield return request6;
            request6 = null;

            WebTestRequest request7 = new WebTestRequest("http://platform.twitter.com/widgets/follow_button.c633b87376883931e7436b93bb46a69" +
                    "9.en.html");
            request7.ThinkTime = 1;
            request7.ExpectedResponseUrl = "http://platform.twitter.com/widgets/follow_button.c633b87376883931e7436b93bb46a69" +
                "9.en.html#_=1450421039778&dnt=false&id=twitter-widget-0&lang=en&screen_name=usga" +
                "&show_count=false&show_screen_name=false&size=m";
            request7.Headers.Add(new WebTestRequestHeader("Referer", "http://www.usga.org/"));
            yield return request7;
            request7 = null;

            WebTestRequest request8 = new WebTestRequest("http://staticxx.facebook.com/connect/xd_arbiter.php");
            request8.ExpectedResponseUrl = "http://staticxx.facebook.com/connect/xd_arbiter.php?version=42#channel=f3ad064435" +
                "da49&origin=http%3A%2F%2Fwww.usga.org";
            request8.QueryStringParameters.Add("version", "42", false, false);
            request8.QueryStringParameters.Add("origin", "http%3A%2F%2Fwww.usga.org", false, false);
            yield return request8;
            request8 = null;

            WebTestRequest request9 = new WebTestRequest("https://staticxx.facebook.com/connect/xd_arbiter.php");
            request9.ExpectedResponseUrl = "https://staticxx.facebook.com/connect/xd_arbiter.php?version=42#channel=f3ad06443" +
                "5da49&origin=http%3A%2F%2Fwww.usga.org";
            request9.QueryStringParameters.Add("version", "42", false, false);
            request9.QueryStringParameters.Add("origin", "http%3A%2F%2Fwww.usga.org", false, false);
            yield return request9;
            request9 = null;

            WebTestRequest request10 = new WebTestRequest("http://staticxx.facebook.com/connect/xd_arbiter.php");
            request10.Headers.Add(new WebTestRequestHeader("Referer", "http://www.usga.org/"));
            request10.QueryStringParameters.Add("version", "42", false, false);
            yield return request10;
            request10 = null;

            WebTestRequest request11 = new WebTestRequest("https://staticxx.facebook.com/connect/xd_arbiter.php");
            request11.Headers.Add(new WebTestRequestHeader("Referer", "http://www.usga.org/"));
            request11.QueryStringParameters.Add("version", "42", false, false);
            yield return request11;
            request11 = null;

            WebTestRequest request12 = new WebTestRequest("https://www.facebook.com/connect/ping");
            request12.Headers.Add(new WebTestRequestHeader("Referer", "http://www.usga.org/"));
            request12.QueryStringParameters.Add("client_id", "1531450863841164", false, false);
            request12.QueryStringParameters.Add("domain", "www.usga.org", false, false);
            request12.QueryStringParameters.Add("origin", "1", false, false);
            request12.QueryStringParameters.Add("redirect_uri", "http%3A%2F%2Fstaticxx.facebook.com%2Fconnect%2Fxd_arbiter.php%3Fversion%3D42%23cb" +
                    "%3Df2c405593ba8dd8%26domain%3Dwww.usga.org%26origin%3Dhttp%253A%252F%252Fwww.usg" +
                    "a.org%252Ff3ad064435da49%26relation%3Dparent", false, false);
            request12.QueryStringParameters.Add("response_type", "token%2Csigned_request%2Ccode", false, false);
            request12.QueryStringParameters.Add("sdk", "joey", false, false);
            yield return request12;
            request12 = null;

            WebTestRequest request13 = new WebTestRequest("http://www.facebook.com/v2.5/plugins/like.php");
            request13.ExpectedResponseUrl = @"https://www.facebook.com/v2.5/plugins/like.php?action=like&app_id=1531450863841164&channel=http%3A%2F%2Fstaticxx.facebook.com%2Fconnect%2Fxd_arbiter.php%3Fversion%3D42%23cb%3Df3276fdf2847ce%26domain%3Dwww.usga.org%26origin%3Dhttp%253A%252F%252Fwww.usga.org%252Ff3ad064435da49%26relation%3Dparent.parent&container_width=102&href=http%3A%2F%2Fwww.usga.org%2F&layout=button&locale=en_US&sdk=joey&share=false&show_faces=false";
            request13.Headers.Add(new WebTestRequestHeader("Referer", "http://www.usga.org/"));
            request13.QueryStringParameters.Add("action", "like", false, false);
            request13.QueryStringParameters.Add("app_id", "1531450863841164", false, false);
            request13.QueryStringParameters.Add("channel", "http%3A%2F%2Fstaticxx.facebook.com%2Fconnect%2Fxd_arbiter.php%3Fversion%3D42%23cb" +
                    "%3Df3276fdf2847ce%26domain%3Dwww.usga.org%26origin%3Dhttp%253A%252F%252Fwww.usga" +
                    ".org%252Ff3ad064435da49%26relation%3Dparent.parent", false, false);
            request13.QueryStringParameters.Add("container_width", "102", false, false);
            request13.QueryStringParameters.Add("href", "http%3A%2F%2Fwww.usga.org%2F", false, false);
            request13.QueryStringParameters.Add("layout", "button", false, false);
            request13.QueryStringParameters.Add("locale", "en_US", false, false);
            request13.QueryStringParameters.Add("sdk", "joey", false, false);
            request13.QueryStringParameters.Add("share", "false", false, false);
            request13.QueryStringParameters.Add("show_faces", "false", false, false);
            yield return request13;
            request13 = null;

            WebTestRequest request14 = new WebTestRequest("http://gscounters.us1.gigya.com/gscounters.sendReport");
            request14.Headers.Add(new WebTestRequestHeader("Referer", "http://www.usga.org/"));
            request14.QueryStringParameters.Add("reports", "%5B%7B%22name%22%3A%22loadc%22%2C%22time%22%3A%221450421036120%22%2C%22reportData" +
                    "%22%3A%7B%22sref%22%3A%22%22%7D%7D%5D", false, false);
            request14.QueryStringParameters.Add("APIKey", "3_2XjOryTsvLPQvhvmmwB8TY-OB_6VT05LD5NVNZjYl1TTvIhq_2kEmKcC9MG1LbVw", false, false);
            request14.QueryStringParameters.Add("sdk", "js_5.8.10", false, false);
            request14.QueryStringParameters.Add("format", "jsonp", false, false);
            request14.QueryStringParameters.Add("callback", "gigya._.apiAdapters.web.callback", false, false);
            request14.QueryStringParameters.Add("context", "R2726380588", false, false);
            yield return request14;
            request14 = null;

            WebTestRequest request15 = new WebTestRequest("http://www.facebook.com/v2.5/plugins/like.php");
            request15.ThinkTime = 6;
            request15.ExpectedResponseUrl = @"https://www.facebook.com/v2.5/plugins/like.php?action=like&app_id=1531450863841164&channel=http%3A%2F%2Fstaticxx.facebook.com%2Fconnect%2Fxd_arbiter.php%3Fversion%3D42%23cb%3Df10d3f460cb0b3%26domain%3Dwww.usga.org%26origin%3Dhttp%253A%252F%252Fwww.usga.org%252Ff3ad064435da49%26relation%3Dparent.parent&container_width=0&href=http%3A%2F%2Fwww.usga.org%2F&layout=button&locale=en_US&sdk=joey&share=false&show_faces=false";
            request15.Headers.Add(new WebTestRequestHeader("Referer", "http://www.usga.org/"));
            request15.QueryStringParameters.Add("action", "like", false, false);
            request15.QueryStringParameters.Add("app_id", "1531450863841164", false, false);
            request15.QueryStringParameters.Add("channel", "http%3A%2F%2Fstaticxx.facebook.com%2Fconnect%2Fxd_arbiter.php%3Fversion%3D42%23cb" +
                    "%3Df10d3f460cb0b3%26domain%3Dwww.usga.org%26origin%3Dhttp%253A%252F%252Fwww.usga" +
                    ".org%252Ff3ad064435da49%26relation%3Dparent.parent", false, false);
            request15.QueryStringParameters.Add("container_width", "0", false, false);
            request15.QueryStringParameters.Add("href", "http%3A%2F%2Fwww.usga.org%2F", false, false);
            request15.QueryStringParameters.Add("layout", "button", false, false);
            request15.QueryStringParameters.Add("locale", "en_US", false, false);
            request15.QueryStringParameters.Add("sdk", "joey", false, false);
            request15.QueryStringParameters.Add("share", "false", false, false);
            request15.QueryStringParameters.Add("show_faces", "false", false, false);
            yield return request15;
            request15 = null;

            WebTestRequest request16 = new WebTestRequest("http://account.usga.org/Login.aspx");
            request16.Headers.Add(new WebTestRequestHeader("Referer", "http://www.usga.org/"));
            request16.QueryStringParameters.Add("", "1450421048087", false, false);
            request16.QueryStringParameters.Add("gtmAccountId", "GTM-T4VLP7", false, false);
            request16.QueryStringParameters.Add("email", "", false, false);
            request16.QueryStringParameters.Add("campaign", "true", false, false);
            ExtractHiddenFields extractionRule2 = new ExtractHiddenFields();
            extractionRule2.Required = true;
            extractionRule2.HtmlDecode = true;
            extractionRule2.ContextParameterName = "1";
            request16.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule2.Extract);
            yield return request16;
            request16 = null;

            WebTestRequest request17 = new WebTestRequest("http://20667643p.rfihub.com/ca.html");
            request17.Headers.Add(new WebTestRequestHeader("Referer", "http://account.usga.org/Login.aspx?1450421048087&gtmAccountId=GTM-T4VLP7&email=&c" +
                        "ampaign=true"));
            request17.QueryStringParameters.Add("ver", "9", false, false);
            request17.QueryStringParameters.Add("rb", "19027", false, false);
            request17.QueryStringParameters.Add("ca", "20667643", false, false);
            request17.QueryStringParameters.Add("pe", "http%3A%2F%2Faccount.usga.org%2FLogin.aspx%3F1450421048087%26gtmAccountId%3DGTM-T" +
                    "4VLP7%26email%3D%26campaign%3Dtrue", false, false);
            request17.QueryStringParameters.Add("pf", "http%3A%2F%2Fwww.usga.org%2F", false, false);
            request17.QueryStringParameters.Add("ra", "5336141168308814", false, false);
            yield return request17;
            request17 = null;

            WebTestRequest request18 = new WebTestRequest("https://googleads.g.doubleclick.net/pagead/viewthroughconversion/961032657/");
            request18.ThinkTime = 2;
            request18.ExpectedResponseUrl = "https://www.google.co.in/ads/user-lists/961032657/?fmt=1&num=1&cv=8&frm=2&url=htt" +
                "p%3A//account.usga.org/Login.aspx%3F1450421048087%26gtmAccountId%3DGTM-T4VLP7%26" +
                "email%3D%26campaign%3Dtrue&ref=http%3A//www.usga.org/&random=1592133487&ipr=y";
            request18.Headers.Add(new WebTestRequestHeader("Referer", "http://account.usga.org/Login.aspx?1450421048087&gtmAccountId=GTM-T4VLP7&email=&c" +
                        "ampaign=true"));
            request18.QueryStringParameters.Add("random", "1450421048831", false, false);
            request18.QueryStringParameters.Add("cv", "8", false, false);
            request18.QueryStringParameters.Add("fst", "1450421048831", false, false);
            request18.QueryStringParameters.Add("num", "1", false, false);
            request18.QueryStringParameters.Add("fmt", "1", false, false);
            request18.QueryStringParameters.Add("guid", "ON", false, false);
            request18.QueryStringParameters.Add("u_h", "1113", false, false);
            request18.QueryStringParameters.Add("u_w", "1391", false, false);
            request18.QueryStringParameters.Add("u_ah", "1061", false, false);
            request18.QueryStringParameters.Add("u_aw", "1391", false, false);
            request18.QueryStringParameters.Add("u_cd", "24", false, false);
            request18.QueryStringParameters.Add("u_his", "1", false, false);
            request18.QueryStringParameters.Add("u_tz", "330", false, false);
            request18.QueryStringParameters.Add("u_java", "true", false, false);
            request18.QueryStringParameters.Add("u_nplug", "2", false, false);
            request18.QueryStringParameters.Add("u_nmime", "4", false, false);
            request18.QueryStringParameters.Add("frm", "2", false, false);
            request18.QueryStringParameters.Add("url", "http%3A//account.usga.org/Login.aspx%3F1450421048087%26gtmAccountId%3DGTM-T4VLP7%" +
                    "26email%3D%26campaign%3Dtrue", false, false);
            request18.QueryStringParameters.Add("ref", "http%3A//www.usga.org/", false, false);
            yield return request18;
            request18 = null;

            WebTestRequest request19 = new WebTestRequest("http://gscounters.us1.gigya.com/gscounters.sendReport");
            request19.ThinkTime = 9;
            request19.Headers.Add(new WebTestRequestHeader("Referer", "http://account.usga.org/Login.aspx?1450421048087&gtmAccountId=GTM-T4VLP7&email=&c" +
                        "ampaign=true"));
            request19.QueryStringParameters.Add("reports", @"%5B%7B%22name%22%3A%22loadc%22%2C%22time%22%3A%221450421048707%22%2C%22reportData%22%3A%7B%22sref%22%3A%22http%3A%2F%2Fwww.usga.org%2F%22%7D%7D%2C%7B%22name%22%3A%22load%22%2C%22time%22%3A%221450421049205%22%2C%22source%22%3A%22showLoginUI%22%2C%22reportData%22%3A%7B%7D%7D%5D", false, false);
            request19.QueryStringParameters.Add("APIKey", "3_2XjOryTsvLPQvhvmmwB8TY-OB_6VT05LD5NVNZjYl1TTvIhq_2kEmKcC9MG1LbVw", false, false);
            request19.QueryStringParameters.Add("sdk", "js_5.8.10", false, false);
            request19.QueryStringParameters.Add("format", "jsonp", false, false);
            request19.QueryStringParameters.Add("callback", "gigya._.apiAdapters.web.callback", false, false);
            request19.QueryStringParameters.Add("context", "R3443125277", false, false);
            yield return request19;
            request19 = null;

            WebTestRequest request20 = new WebTestRequest("http://account.usga.org/Login.aspx");
            request20.Method = "POST";
            request20.Headers.Add(new WebTestRequestHeader("Referer", "http://account.usga.org/Login.aspx?1450421048087&gtmAccountId=GTM-T4VLP7&email=&c" +
                        "ampaign=true"));
            request20.QueryStringParameters.Add("", "1450421048087", false, false);
            request20.QueryStringParameters.Add("gtmAccountId", "GTM-T4VLP7", false, false);
            request20.QueryStringParameters.Add("email", "", false, false);
            request20.QueryStringParameters.Add("campaign", "true", false, false);
            FormPostHttpBody request20Body = new FormPostHttpBody();
            request20Body.FormPostParameters.Add("__EVENTTARGET", this.Context["$HIDDEN1.__EVENTTARGET"].ToString());
            request20Body.FormPostParameters.Add("__EVENTARGUMENT", this.Context["$HIDDEN1.__EVENTARGUMENT"].ToString());
            request20Body.FormPostParameters.Add("__VIEWSTATE", this.Context["$HIDDEN1.__VIEWSTATE"].ToString());
            request20Body.FormPostParameters.Add("__VIEWSTATEGENERATOR", this.Context["$HIDDEN1.__VIEWSTATEGENERATOR"].ToString());
            request20Body.FormPostParameters.Add("__EVENTVALIDATION", this.Context["$HIDDEN1.__EVENTVALIDATION"].ToString());
            request20Body.FormPostParameters.Add("ctl00$Content$emailTextBox", "anuj_rov@yahoo.com");
            request20Body.FormPostParameters.Add("ctl00$Content$passwordTextBox", "Deloitte.1");
            request20Body.FormPostParameters.Add("ctl00$Content$loginButton", "Sign In");
            request20.Body = request20Body;
            WebTestRequest request20Dependent1 = new WebTestRequest("https://socialize.us1.gigya.com/socialize.notifyLogin");
            request20Dependent1.Headers.Add(new WebTestRequestHeader("Referer", "http://account.usga.org/Login.aspx?1450421048087&gtmAccountId=GTM-T4VLP7&email=&c" +
                        "ampaign=true"));
            request20Dependent1.QueryStringParameters.Add("sessionExpiration", "0", false, false);
            request20Dependent1.QueryStringParameters.Add("authCode", @"VC1_98D7F44C9ABC12142EF04DB668AB57BC_0oma1oV2HDliUrqGzh8tgOnfP_vXN7f1ywM5er0s6lCiWUCbXveH4WTYWQhpLJzbi4E6IvELSjE_9wX-BVcUBCnYcsEV8SN_4n4OlrQCQu1cIuU09BTZnfp74G1uZ3ibKbolQuLp3QdT5MJg6Vbgudj7sO2Eg9nVXsA9lRGFaJxi4JRY6HgBMwxJ-ghl3q7MgakY9Akr9IV3VeqxwVVn9g%3D%3D", false, false);
            request20Dependent1.QueryStringParameters.Add("APIKey", "3_2XjOryTsvLPQvhvmmwB8TY-OB_6VT05LD5NVNZjYl1TTvIhq_2kEmKcC9MG1LbVw", false, false);
            request20Dependent1.QueryStringParameters.Add("sdk", "js_5.8.10", false, false);
            request20Dependent1.QueryStringParameters.Add("format", "jsonp", false, false);
            request20Dependent1.QueryStringParameters.Add("callback", "gigya._.apiAdapters.web.callback", false, false);
            request20Dependent1.QueryStringParameters.Add("context", "R558344797", false, false);
            request20Dependent1.QueryStringParameters.Add("authMode", "cookie", false, false);
            request20.DependentRequests.Add(request20Dependent1);
            ExtractHiddenFields extractionRule3 = new ExtractHiddenFields();
            extractionRule3.Required = true;
            extractionRule3.HtmlDecode = true;
            extractionRule3.ContextParameterName = "1";
            request20.ExtractValues += new EventHandler<ExtractionEventArgs>(extractionRule3.Extract);
            yield return request20;
            request20 = null;

            WebTestRequest request21 = new WebTestRequest("http://20667643p.rfihub.com/ca.html");
            request21.Headers.Add(new WebTestRequestHeader("Referer", "http://account.usga.org/Login.aspx?1450421048087&gtmAccountId=GTM-T4VLP7&email=&c" +
                        "ampaign=true"));
            request21.QueryStringParameters.Add("ver", "9", false, false);
            request21.QueryStringParameters.Add("rb", "19027", false, false);
            request21.QueryStringParameters.Add("ca", "20667643", false, false);
            request21.QueryStringParameters.Add("pe", "http%3A%2F%2Faccount.usga.org%2FLogin.aspx%3F1450421048087%26gtmAccountId%3DGTM-T" +
                    "4VLP7%26email%3D%26campaign%3Dtrue", false, false);
            request21.QueryStringParameters.Add("pf", "http%3A%2F%2Faccount.usga.org%2FLogin.aspx%3F1450421048087%26gtmAccountId%3DGTM-T" +
                    "4VLP7%26email%3D%26campaign%3Dtrue", false, false);
            request21.QueryStringParameters.Add("ra", "5799235570160348", false, false);
            yield return request21;
            request21 = null;

            WebTestRequest request22 = new WebTestRequest("https://googleads.g.doubleclick.net/pagead/viewthroughconversion/961032657/");
            request22.ExpectedResponseUrl = @"https://www.google.co.in/ads/user-lists/961032657/?fmt=1&num=1&cv=8&frm=2&url=http%3A//account.usga.org/Login.aspx%3F1450421048087%26gtmAccountId%3DGTM-T4VLP7%26email%3D%26campaign%3Dtrue&ref=http%3A//account.usga.org/Login.aspx%3F1450421048087%26gtmAccountId%3DGTM-T4VLP7%26email%3D%26campaign%3Dtrue&random=1743286540&ipr=y";
            request22.Headers.Add(new WebTestRequestHeader("Referer", "http://account.usga.org/Login.aspx?1450421048087&gtmAccountId=GTM-T4VLP7&email=&c" +
                        "ampaign=true"));
            request22.QueryStringParameters.Add("random", "1450421064486", false, false);
            request22.QueryStringParameters.Add("cv", "8", false, false);
            request22.QueryStringParameters.Add("fst", "1450421064486", false, false);
            request22.QueryStringParameters.Add("num", "1", false, false);
            request22.QueryStringParameters.Add("fmt", "1", false, false);
            request22.QueryStringParameters.Add("guid", "ON", false, false);
            request22.QueryStringParameters.Add("u_h", "1113", false, false);
            request22.QueryStringParameters.Add("u_w", "1391", false, false);
            request22.QueryStringParameters.Add("u_ah", "1061", false, false);
            request22.QueryStringParameters.Add("u_aw", "1391", false, false);
            request22.QueryStringParameters.Add("u_cd", "24", false, false);
            request22.QueryStringParameters.Add("u_his", "2", false, false);
            request22.QueryStringParameters.Add("u_tz", "330", false, false);
            request22.QueryStringParameters.Add("u_java", "true", false, false);
            request22.QueryStringParameters.Add("u_nplug", "2", false, false);
            request22.QueryStringParameters.Add("u_nmime", "4", false, false);
            request22.QueryStringParameters.Add("frm", "2", false, false);
            request22.QueryStringParameters.Add("url", "http%3A//account.usga.org/Login.aspx%3F1450421048087%26gtmAccountId%3DGTM-T4VLP7%" +
                    "26email%3D%26campaign%3Dtrue", false, false);
            request22.QueryStringParameters.Add("ref", "http%3A//account.usga.org/Login.aspx%3F1450421048087%26gtmAccountId%3DGTM-T4VLP7%" +
                    "26email%3D%26campaign%3Dtrue", false, false);
            yield return request22;
            request22 = null;

            WebTestRequest request23 = new WebTestRequest("https://socialize.us1.gigya.com/socialize.getUserInfo");
            request23.Headers.Add(new WebTestRequestHeader("Referer", "http://account.usga.org/Login.aspx?1450421048087&gtmAccountId=GTM-T4VLP7&email=&c" +
                        "ampaign=true"));
            request23.QueryStringParameters.Add("APIKey", "3_2XjOryTsvLPQvhvmmwB8TY-OB_6VT05LD5NVNZjYl1TTvIhq_2kEmKcC9MG1LbVw", false, false);
            request23.QueryStringParameters.Add("sdk", "js_5.8.10", false, false);
            request23.QueryStringParameters.Add("format", "jsonp", false, false);
            request23.QueryStringParameters.Add("callback", "gigya._.apiAdapters.web.callback", false, false);
            request23.QueryStringParameters.Add("context", "R697004265", false, false);
            request23.QueryStringParameters.Add("login_token", "LT3_n_1NmL5HwMatKbbab-TIJzkfwbLNC72yHwRCOQc3AXA", false, false);
            request23.QueryStringParameters.Add("authMode", "cookie", false, false);
            yield return request23;
            request23 = null;

            WebTestRequest request24 = new WebTestRequest("http://www.usga.org/bin/data/feeds/ticker.json");
            request24.Headers.Add(new WebTestRequestHeader("Accept", "*/*"));
            request24.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json"));
            request24.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request24.Headers.Add(new WebTestRequestHeader("Referer", "http://www.usga.org/"));
            yield return request24;
            request24 = null;

            WebTestRequest request25 = new WebTestRequest("http://account.usga.org/LoginValidate.aspx");
            request25.Method = "POST";
            request25.Headers.Add(new WebTestRequestHeader("Referer", "http://account.usga.org/Login.aspx?1450421048087&gtmAccountId=GTM-T4VLP7&email=&c" +
                        "ampaign=true"));
            FormPostHttpBody request25Body = new FormPostHttpBody();
            request25Body.FormPostParameters.Add("LoginSuccessUrl", this.Context["$HIDDEN1.LoginSuccessUrl"].ToString());
            request25Body.FormPostParameters.Add("UID", "374a5c717e3344d083e84ef8c42881d8");
            request25Body.FormPostParameters.Add("UIDSignature", "4jUKxnTWkDS7dJmWV9xpTXIe9pY=");
            request25Body.FormPostParameters.Add("SignatureTimestamp", "1450421066");
            request25.Body = request25Body;
            yield return request25;
            request25 = null;

            WebTestRequest request26 = new WebTestRequest("https://socialize.us1.gigya.com/socialize.notifyLogin");
            request26.Headers.Add(new WebTestRequestHeader("Referer", "http://account.usga.org/LoginValidate.aspx"));
            request26.QueryStringParameters.Add("siteUID", "374a5c717e3344d083e84ef8c42881d8", false, false);
            request26.QueryStringParameters.Add("UIDTimestamp", "1450421066", false, false);
            request26.QueryStringParameters.Add("UIDSig", "4jUKxnTWkDS7dJmWV9xpTXIe9pY%3D", false, false);
            request26.QueryStringParameters.Add("sessionExpiration", "0", false, false);
            request26.QueryStringParameters.Add("APIKey", "3_2XjOryTsvLPQvhvmmwB8TY-OB_6VT05LD5NVNZjYl1TTvIhq_2kEmKcC9MG1LbVw", false, false);
            request26.QueryStringParameters.Add("sdk", "js_5.8.10", false, false);
            request26.QueryStringParameters.Add("format", "jsonp", false, false);
            request26.QueryStringParameters.Add("callback", "gigya._.apiAdapters.web.callback", false, false);
            request26.QueryStringParameters.Add("context", "R2348401649", false, false);
            request26.QueryStringParameters.Add("authMode", "cookie", false, false);
            yield return request26;
            request26 = null;

            WebTestRequest request27 = new WebTestRequest("https://accounts.us1.gigya.com/accounts.getAccountInfo");
            request27.Headers.Add(new WebTestRequestHeader("Referer", "http://www.usga.org/"));
            request27.QueryStringParameters.Add("include", "profile%2Cdata%2C", false, false);
            request27.QueryStringParameters.Add("extraProfileFields", "address%2Cphones", false, false);
            request27.QueryStringParameters.Add("APIKey", "3_2XjOryTsvLPQvhvmmwB8TY-OB_6VT05LD5NVNZjYl1TTvIhq_2kEmKcC9MG1LbVw", false, false);
            request27.QueryStringParameters.Add("sdk", "js_5.8.10", false, false);
            request27.QueryStringParameters.Add("format", "jsonp", false, false);
            request27.QueryStringParameters.Add("callback", "gigya._.apiAdapters.web.callback", false, false);
            request27.QueryStringParameters.Add("context", "R2452641462", false, false);
            request27.QueryStringParameters.Add("login_token", "LT3_MWEBBrBTtF6Y5TyK6ArqBY3OvUfMoiKCFN2XTpg1tdM", false, false);
            request27.QueryStringParameters.Add("authMode", "cookie", false, false);
            yield return request27;
            request27 = null;

            WebTestRequest request28 = new WebTestRequest("https://ds.us1.gigya.com/ds.get");
            request28.ThinkTime = 3;
            request28.Headers.Add(new WebTestRequestHeader("Referer", "http://www.usga.org/"));
            request28.QueryStringParameters.Add("type", "Member", false, false);
            request28.QueryStringParameters.Add("oid", "374a5c717e3344d083e84ef8c42881d8", false, false);
            request28.QueryStringParameters.Add("APIKey", "3_2XjOryTsvLPQvhvmmwB8TY-OB_6VT05LD5NVNZjYl1TTvIhq_2kEmKcC9MG1LbVw", false, false);
            request28.QueryStringParameters.Add("sdk", "js_5.8.10", false, false);
            request28.QueryStringParameters.Add("format", "jsonp", false, false);
            request28.QueryStringParameters.Add("callback", "gigya._.apiAdapters.web.callback", false, false);
            request28.QueryStringParameters.Add("context", "R31343727", false, false);
            request28.QueryStringParameters.Add("login_token", "LT3_MWEBBrBTtF6Y5TyK6ArqBY3OvUfMoiKCFN2XTpg1tdM", false, false);
            request28.QueryStringParameters.Add("authMode", "cookie", false, false);
            yield return request28;
            request28 = null;

            WebTestRequest request29 = new WebTestRequest("http://gscounters.us1.gigya.com/gscounters.sendReport");
            request29.ThinkTime = 33;
            request29.Headers.Add(new WebTestRequestHeader("Referer", "http://account.usga.org/LoginValidate.aspx"));
            request29.QueryStringParameters.Add("reports", "%5B%7B%22name%22%3A%22loadc%22%2C%22time%22%3A%221450421067250%22%2C%22reportData" +
                    "%22%3A%7B%22sref%22%3A%22http%3A%2F%2Faccount.usga.org%2FLogin.aspx%3F1450421048" +
                    "087%26gtmAccountId%3DGTM-T4VLP7%26email%3D%26campaign%3Dtrue%22%7D%7D%5D", false, false);
            request29.QueryStringParameters.Add("APIKey", "3_2XjOryTsvLPQvhvmmwB8TY-OB_6VT05LD5NVNZjYl1TTvIhq_2kEmKcC9MG1LbVw", false, false);
            request29.QueryStringParameters.Add("sdk", "js_5.8.10", false, false);
            request29.QueryStringParameters.Add("format", "jsonp", false, false);
            request29.QueryStringParameters.Add("callback", "gigya._.apiAdapters.web.callback", false, false);
            request29.QueryStringParameters.Add("context", "R2825511245", false, false);
            yield return request29;
            request29 = null;

            WebTestRequest request30 = new WebTestRequest("http://account.usga.org/Logout.aspx");
            request30.Headers.Add(new WebTestRequestHeader("Referer", "http://www.usga.org/"));
            request30.QueryStringParameters.Add("", "", false, false);
            request30.QueryStringParameters.Add("gtmAccountId", "GTM-T4VLP7", false, false);
            request30.QueryStringParameters.Add("email", "", false, false);
            request30.QueryStringParameters.Add("campaign", "", false, false);
            yield return request30;
            request30 = null;

            WebTestRequest request31 = new WebTestRequest("https://socialize.us1.gigya.com/socialize.logout");
            request31.Headers.Add(new WebTestRequestHeader("Referer", "http://account.usga.org/Logout.aspx?&gtmAccountId=GTM-T4VLP7&email=&campaign="));
            request31.QueryStringParameters.Add("APIKey", "3_2XjOryTsvLPQvhvmmwB8TY-OB_6VT05LD5NVNZjYl1TTvIhq_2kEmKcC9MG1LbVw", false, false);
            request31.QueryStringParameters.Add("sdk", "js_5.8.10", false, false);
            request31.QueryStringParameters.Add("format", "jsonp", false, false);
            request31.QueryStringParameters.Add("callback", "gigya._.apiAdapters.web.callback", false, false);
            request31.QueryStringParameters.Add("context", "R709986576", false, false);
            request31.QueryStringParameters.Add("login_token", "LT3_MWEBBrBTtF6Y5TyK6ArqBY3OvUfMoiKCFN2XTpg1tdM", false, false);
            request31.QueryStringParameters.Add("authMode", "cookie", false, false);
            yield return request31;
            request31 = null;
        }
    }
}
