//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USGA.PerformanceTest.R1
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using Microsoft.VisualStudio.TestTools.WebTesting;
    using System.Diagnostics;
    using System.Linq;
    using System.Threading.Tasks;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using System.Windows.Forms;
    using System.Drawing;



    [Priority(0)]
    public class FromFiddlerWebtestYahooMailCoded : WebTest
    {

        public FromFiddlerWebtestYahooMailCoded()
        {
            this.PreAuthenticate = true;
            this.Proxy = "default";
        }

        public override IEnumerator<WebTestRequest> GetRequestEnumerator()
        {
            WebTestRequest request1 = new WebTestRequest("https://www.telerik.com/UpdateCheck.aspx");
            request1.ThinkTime = 21;
            request1.Timeout = 60;
            request1.Headers.Add(new WebTestRequestHeader("Pragma", "no-cache"));
            request1.QueryStringParameters.Add("isBeta", "False");
            yield return request1;
            request1 = null;

            WebTestRequest request2 = new WebTestRequest("http://api.bing.com/qsml.aspx");
            request2.Timeout = 60;
            request2.Headers.Add(new WebTestRequestHeader("DNT", "1"));
            request2.QueryStringParameters.Add("query", "y");
            request2.QueryStringParameters.Add("maxwidth", "32765");
            request2.QueryStringParameters.Add("rowheight", "26");
            request2.QueryStringParameters.Add("sectionHeight", "208");
            request2.QueryStringParameters.Add("FORM", "IESS02");
            request2.QueryStringParameters.Add("market", "en-US");
            yield return request2;
            request2 = null;

            WebTestRequest request3 = new WebTestRequest("http://api.bing.com/qsml.aspx");
            request3.Timeout = 60;
            request3.Headers.Add(new WebTestRequestHeader("DNT", "1"));
            request3.QueryStringParameters.Add("query", "ya");
            request3.QueryStringParameters.Add("maxwidth", "32765");
            request3.QueryStringParameters.Add("rowheight", "26");
            request3.QueryStringParameters.Add("sectionHeight", "208");
            request3.QueryStringParameters.Add("FORM", "IESS02");
            request3.QueryStringParameters.Add("market", "en-US");
            yield return request3;
            request3 = null;

            WebTestRequest request4 = new WebTestRequest("http://api.bing.com/qsml.aspx");
            request4.Timeout = 60;
            request4.Headers.Add(new WebTestRequestHeader("DNT", "1"));
            request4.QueryStringParameters.Add("query", "yah");
            request4.QueryStringParameters.Add("maxwidth", "32765");
            request4.QueryStringParameters.Add("rowheight", "26");
            request4.QueryStringParameters.Add("sectionHeight", "208");
            request4.QueryStringParameters.Add("FORM", "IESS02");
            request4.QueryStringParameters.Add("market", "en-US");
            yield return request4;
            request4 = null;

            WebTestRequest request5 = new WebTestRequest("http://api.bing.com/qsml.aspx");
            request5.Timeout = 60;
            request5.Headers.Add(new WebTestRequestHeader("DNT", "1"));
            request5.QueryStringParameters.Add("query", "yaho");
            request5.QueryStringParameters.Add("maxwidth", "32765");
            request5.QueryStringParameters.Add("rowheight", "26");
            request5.QueryStringParameters.Add("sectionHeight", "208");
            request5.QueryStringParameters.Add("FORM", "IESS02");
            request5.QueryStringParameters.Add("market", "en-US");
            yield return request5;
            request5 = null;

            WebTestRequest request6 = new WebTestRequest("http://api.bing.com/qsml.aspx");
            request6.Timeout = 60;
            request6.Headers.Add(new WebTestRequestHeader("DNT", "1"));
            request6.QueryStringParameters.Add("query", "yahoo");
            request6.QueryStringParameters.Add("maxwidth", "32765");
            request6.QueryStringParameters.Add("rowheight", "26");
            request6.QueryStringParameters.Add("sectionHeight", "208");
            request6.QueryStringParameters.Add("FORM", "IESS02");
            request6.QueryStringParameters.Add("market", "en-US");
            yield return request6;
            request6 = null;

            WebTestRequest request7 = new WebTestRequest("http://yahoomail.com/");
            request7.Timeout = 60;
            request7.Headers.Add(new WebTestRequestHeader("DNT", "1"));
            yield return request7;
            request7 = null;

            WebTestRequest request8 = new WebTestRequest("http://ss.symcd.com/MFEwTzBNMEswSTAJBgUrDgMCGgUABBTRsWSLjJ8N0Wujis0rUBfV%2Bc%2FAZ" +
                    "AQUX2DPYZBV34RDFIpgKrL1evRDGO8CEAPWCvc6OmnaFsJ7jE5jV8E%3D");
            request8.ThinkTime = 2;
            request8.Timeout = 60;
            yield return request8;
            request8 = null;

            WebTestRequest request9 = new WebTestRequest("http://ss.symcd.com/MFEwTzBNMEswSTAJBgUrDgMCGgUABBTRsWSLjJ8N0Wujis0rUBfV%2Bc%2FAZ" +
                    "AQUX2DPYZBV34RDFIpgKrL1evRDGO8CEHUSAVHS%2BeKbjmi3VAZfm8k%3D");
            request9.ThinkTime = 1;
            request9.Timeout = 60;
            yield return request9;
            request9 = null;

            WebTestRequest request10 = new WebTestRequest("http://ss.symcd.com/MFEwTzBNMEswSTAJBgUrDgMCGgUABBTRsWSLjJ8N0Wujis0rUBfV%2Bc%2FAZ" +
                    "AQUX2DPYZBV34RDFIpgKrL1evRDGO8CEGYxEdPOwq9cY7LDZtmpRAE%3D");
            request10.Timeout = 60;
            yield return request10;
            request10 = null;

            WebTestRequest request11 = new WebTestRequest("http://vassg142.ocsp.omniroot.com/MFUwUzBRME8wTTAJBgUrDgMCGgUABBTkLVLomfJQOu5CFIg" +
                    "POR73ljBRHAQU%2BL36r3N3xscb%2BUtNEafRM6%2BvchECFChPirZjzI2lcZqys9X5eeuZaCpA");
            request11.Timeout = 60;
            yield return request11;
            request11 = null;

            WebTestRequest request12 = new WebTestRequest("http://ss.symcd.com/MFEwTzBNMEswSTAJBgUrDgMCGgUABBTRsWSLjJ8N0Wujis0rUBfV%2Bc%2FAZ" +
                    "AQUX2DPYZBV34RDFIpgKrL1evRDGO8CEAH7TOm1bUTQQVzg0Pfgmy4%3D");
            request12.Timeout = 60;
            yield return request12;
            request12 = null;

            WebTestRequest request13 = new WebTestRequest("http://ss.symcd.com/MFEwTzBNMEswSTAJBgUrDgMCGgUABBTRsWSLjJ8N0Wujis0rUBfV%2Bc%2FAZ" +
                    "AQUX2DPYZBV34RDFIpgKrL1evRDGO8CEDnQETkANbILqbe3d43Z2iM%3D");
            request13.ThinkTime = 1;
            request13.Timeout = 60;
            yield return request13;
            request13 = null;

            WebTestRequest request14 = new WebTestRequest("http://ss.symcd.com/MFEwTzBNMEswSTAJBgUrDgMCGgUABBTRsWSLjJ8N0Wujis0rUBfV%2Bc%2FAZ" +
                    "AQUX2DPYZBV34RDFIpgKrL1evRDGO8CECfzDmWuAKIUMRRQGE0N4sU%3D");
            request14.ThinkTime = 11;
            request14.Timeout = 60;
            yield return request14;
            request14 = null;

            WebTestRequest request15 = new WebTestRequest("http://ss.symcd.com/MFEwTzBNMEswSTAJBgUrDgMCGgUABBTRsWSLjJ8N0Wujis0rUBfV%2Bc%2FAZ" +
                    "AQUX2DPYZBV34RDFIpgKrL1evRDGO8CEFZ42PCFFBuLCKZNK9CODmE%3D");
            request15.ThinkTime = 3;
            request15.Timeout = 60;
            yield return request15;
            request15 = null;

            WebTestRequest request16 = new WebTestRequest("http://ocsp.godaddy.com//MEowSDBGMEQwQjAJBgUrDgMCGgUABBS2CA1fbGt26xPkOKX4ZguoUjM0" +
                    "TgQUQMK9J47MNIMwojPX%2B2yz8LQsgM4CCQCzUdtZrbpA8g%3D%3D");
            request16.Timeout = 30;
            yield return request16;
            request16 = null;
          
            if (DateTime.Today.DayOfWeek == DayOfWeek.Friday)
            {
                WebTestRequest customRequest = new WebTestRequest("http://weather.msn.com/");
                yield return customRequest;
            }
            else
            {
                WebTestRequest customRequest = new WebTestRequest("http://msdn.microsoft.com/");
                yield return customRequest;
            }
            MessageBox.Show("XYZ validation");
            
        }
    }
}
